# 运行模式(debug:调试,test:测试,release:正式)
runmode = "debug"

# 是否启用swagger
swagger = true

# 启动时是否打印配置参数
printconfig = false

[casbin]
enable = true
model = "./configs/rbac_restful.conf"
policysource = "./configs/rbac_policy.json"

[http]
port = 80

[jwtauth]
signingsecret = "12345678"