# 运行模式(debug:调试,test:测试,release:正式)
RunMode = "debug"

# 是否启用swagger
Swagger = false

# 启动时是否打印配置参数
PrintConfig = true

[HTTP]
Host = "0.0.0.0"
Port = 8081
ShutdownTimeout = 30

[Casbin]
Enable = true
PolicySource = "./configs/rbac_policy.json"
